name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with: 
        submodules: true
    - name: Node App Helper Actions
      run: |
        npm ci
        npm build
        
