name: CI

on:
  push:
    paths:
    - 'angular-submodule-page-1/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: |
        npm ci
        npm build
        
